### ISSUE TITLE
mask縮放問題

### ISSUE THREAD

**Issue by xo0821** [MatchWorkshop/No_18#2]
程式碼在:No_18/Assets/Scripts/PlayerCtrl.cs
在mask縮小的時候，按移動會瞬間跳到初始大小(scale:1,1,1)再慢慢變大到(最大是scale:2,2,2)。
覺得應該是在UnMaskChange這個方法裡面，猜測是沒記錄到值或是其他地方有蓋掉值，但是找不到是哪邊蓋掉。
這個方法主要功能是根據第一個參數調整縮小速度，從第2個參數漸進到第3個參數的值，如果有上下左右其中一個按鍵被按下的話，紀錄當下的scale並結束這個協程。

**Comment by jcs090218** [comment]
我先寫一些我自己的看法, 你的代碼有些凌亂. 特別是沒有一致的規範. 例如,

https://github.com/MatchWorkshop/No_18/blob/3ed62fd087a988f3051d9104e37a23bd26ff2d32/Assets/Scripts/PlayerCtrl.cs#L8

https://github.com/MatchWorkshop/No_18/blob/3ed62fd087a988f3051d9104e37a23bd26ff2d32/Assets/Scripts/PlayerCtrl.cs#L25

兩個同為`public`, 為什麼一個為大寫, 一個則沒有?

---

第二個大問題是, 你的腳本為`PlayerCtrl.cs`. 表示這個為`玩家控制`的責任. 一個好的程序要保持著單一責任的習慣. Mask應該要獨立分開去寫. 這樣思路會比較清晰.

---

回到主題, 你的邏輯有些凌亂. 我建議你可以除掉一些已經assign的地方. 像是,

https://github.com/MatchWorkshop/No_18/blob/3ed62fd087a988f3051d9104e37a23bd26ff2d32/Assets/Scripts/PlayerCtrl.cs#L107

這樣或許能讓你自己的思路比較好理解.

---

然後最後一點, 註解不能少. 你的命名問題是**還好**. 但邏輯部分我會建議加多一些註解.

**Comment by xo0821** [comment]
問題三不太了解意思，是指我不需要用方法去GetPlayerPosition()，而是直接PlayerCtrl.PlayerPosition的方式直接取得值，沒必要再多一個方法的意思嗎？

**Comment by jcs090218** [comment]
因為版本問題, 我沒辦法開啟你的專案. 所以我先假設你的`s`為mask. 如果是, 那`s.transform.localScale = End;`是設定他大小的值, 對吧? 我的意思是, 試著屏除掉一些這類型的operation code, 來看是哪邊出了問題. Debug.Log也可以. 👍

**Comment by xo0821** [comment]
s是mask以及是設定大小值沒錯，好的

**Comment by xo0821** [comment]
我先休息了，明天再嘗試，謝謝～

**Comment by xo0821** [comment]
完成功能了，變成單一責任之後思路清晰很多，謝謝。

**Comment by jcs090218** [comment]
恭喜! 我就把這issue關了! :)
