### ISSUE TITLE
sprite mask跟mask哪個用在目前專案適合的問題

### ISSUE THREAD

**Issue by xo0821** [MatchWorkshop/No_18#3]
目前遮罩是用sprite圖片在sprite mask範圍內才會顯示圖片的方式(sprite mask是用來決定顯示區域)，但是切到wireframe顯示方式去看網格發現有很多三角形的面，不是像image那樣只有2個三角形，不確定如果以後東西變多會不會出問題，因為程式這邊進度目前是落後的，不知道要不要現在換用mask做，還是先維持用sprite mask讓其他成員先往前推進度。
目前比較傾向等到之後出問題再換過去就好，但是不知道後面要改會不會很麻煩，所以想先問看看哪個有可能適合點。

**Comment by jcs090218** [comment]
依我推測, `Mask`應該為`Sprite Mask`的主類別. 這種情況其實最好的做法是用一張美術圖直接, 然後直接放大縮小. 這樣的效果是最理想的. Mask的運用最好是在特定的情況才會使用. 主要是因為Mask會耗一些效能, 用程式改起來也比較麻煩. 通常交由美術去弄是最好的做法. 建議.

如果你們堅持使用Sprite Mask, 那我目前認為沒有太大問題, 如果效能有問題, 那之後再想辦法就好. 0.0

**Comment by xo0821** [comment]
那先維持目前做法推進進度，等到有問題再想辦法好惹，謝謝~
