### ISSUE TITLE
狀態機問題

### ISSUE THREAD

**Issue by xo0821** [MatchWorkshop/No_18#4]
目前是使用
class AI
{
public float speed;
Istate currectState;
MoveState moveState =new MoveState(); 
}

class MoveState:Istate{
//這邊無法取得上面AI類的speed
}

這樣的方式做狀態機，但是對於在MoveState裡面得到AI的speed沒有頭緒，有嘗試過如果把speed改成static就能經由AI.speed拿到，
但是改成static會變成所有ai共用這個speed所以這個方法應該也行不通，想詢問有甚麼方法可以得到speed嗎?還是我有哪邊是錯誤的，或是這個做法不適合應該改用甚麼方式會比較好。

**Comment by jcs090218** [comment]
你可以建立contructor, 並且把AI帶進去就好. :)

**Comment by xo0821** [comment]
謝謝~~~
